# Generated by Django 4.2 on 2023-05-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='order_num',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='order_num',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcatalog',
            name='order_num',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
