# Generated by Django 4.2 on 2023-05-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='image',
            field=models.ImageField(default='no-image.png', upload_to='goods/'),
        ),
    ]
